# Generated by Django 3.0.2 on 2020-02-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botpromokotapp', '0003_auto_20200222_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
    ]
